force-app/main/default/objects/Pandadoc_Quote_Template_Mapping__mdt/Pandadoc_Quote_Template_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Maps Divisions (Slate, Align, Palermo) to the Pandadoc template they use for button-click Quote generation.</description>
    <label>Pandadoc Quote Template Mapping</label>
    <pluralLabel>Pandadoc Quote Template Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pandadoc_Quote_Template_Mapping__mdt/fields/Division_Name__c.field-meta.xml
<CustomField>
    <fullName>Division_Name__c</fullName>
    <label>Division Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pandadoc_Quote_Template_Mapping__mdt/fields/Pandadoc_CC_Fee_Estimate_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Pandadoc_CC_Fee_Estimate_Template_Id__c</fullName>
    <inlineHelpText>The Pandadoc template to use for initial Quotes that include Credit Card fee</inlineHelpText>
    <label>Pandadoc CC Fee Estimate Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pandadoc_Quote_Template_Mapping__mdt/fields/Pandadoc_CC_Fee_Invoice_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Pandadoc_CC_Fee_Invoice_Template_Id__c</fullName>
    <inlineHelpText>Maps to a Pandadoc Invoice template which includes a merge field for credit card fee</inlineHelpText>
    <label>Pandadoc CC Fee Invoice Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pandadoc_Quote_Template_Mapping__mdt/fields/Pandadoc_Estimate_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Pandadoc_Estimate_Template_Id__c</fullName>
    <inlineHelpText>The pandadoc identifier for the template to use for estimate generation</inlineHelpText>
    <label>Pandadoc Estimate Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pandadoc_Quote_Template_Mapping__mdt/fields/Pandadoc_Invoice_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Pandadoc_Invoice_Template_Id__c</fullName>
    <inlineHelpText>The Pandadoc template Id to use for final invoice generation.</inlineHelpText>
    <label>Pandadoc Invoice Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/selectors/PandadocQuoteMappingSelector.cls
public with sharing class PandadocQuoteMappingSelector {
  public PandadocQuoteMappingSelector() {
  }

  public Pandadoc_Quote_Template_Mapping__mdt selectPandadocQuoteTemplateMappingByDivisionName(
    String divisionName
  ) {
    return [
      SELECT
        Division_Name__c,
        Pandadoc_CC_Fee_Estimate_Template_Id__c,
        Pandadoc_Estimate_Template_Id__c,
        Pandadoc_Invoice_Template_Id__c,
        Pandadoc_CC_Fee_Invoice_Template_Id__c,
        Invoice_Pricing_Table_Name__c
      FROM Pandadoc_Quote_Template_Mapping__mdt
      WHERE Division_Name__c = :divisionName
      LIMIT 1
    ];
  }
}