force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>For any clients that are not retainers</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <description>A division of Slate&apos;s business, either &quot;Slate&quot;, &quot;Palermo&quot; or &quot;Align&quot; at time of writing.</description>
    <label>Division</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Total # of Shoot Days for Opp
Used by Calendar to Lookup Opp Start Date and auto calculate Opp End Date</description>
    <inlineHelpText>Total # of Shoot Days for Opp
Used by Calendar to Lookup Opp Start Date and auto calculate Opp End Date</inlineHelpText>
    <label>Shoot Date - # Days</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The business division to which this Opportunity applies. The Division Leader is responsible for closing this deal.</description>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Producer__c.field-meta.xml
<CustomField>
    <fullName>Lead_Producer__c</fullName>
    <description>This is a Single Picklist Field to enter the Lead Producer for each Opportunity
This field is important for Reporting Dashboards for Employee Performance and also allows Lead Producers to sort the Opportunity Pipeline Views to show only their assigned Projects.</description>
    <inlineHelpText>This is a Single Picklist Field to enter the Lead Producer for each Opportunity
This field is important for Reporting Dashboards for Employee Performance and also allows Lead Producers to sort the Opportunity Pipeline Views to show only their assigned Projects.</inlineHelpText>
    <label>Lead Producer</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Heather Cullum</fullName>
                <default>true</default>
                <label>Heather Cullum</label>
            </value>
            <value>
                <fullName>Ferhat Yurdam</fullName>
            </value>
            <value>
                <fullName>Cameron Krone</fullName>
            </value>
            <value>
                <fullName>Regina Bakeeva</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <description>Svc Type (Required) – Must be entered when creating an Opp.
Syncs with Auto Quote Builder to generate quotes based on Svc Type.</description>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand Content</fullName>
                <label>Slate - Brand Content</label>
            </value>
            <value>
                <fullName>Slate - CGI</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
                <default>true</default>
                <label>Slate - eCom</label>
            </value>
            <value>
                <fullName>Motion</fullName>
                <label>Slate - Motion</label>
            </value>
            <value>
                <fullName>Retouching</fullName>
                <label>Slate - Retouch</label>
            </value>
            <value>
                <fullName>Studio Rental</fullName>
                <label>Slate - Studio &amp; Eq</label>
            </value>
            <value>
                <fullName>Retouching - Align</fullName>
                <label>Align - Retouch</label>
            </value>
            <value>
                <fullName>Palermo - Branding</fullName>
            </value>
            <value>
                <fullName>Palermo - Video Production</fullName>
                <label>Palermo - Content</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Post Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Post Production</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Production</label>
            </value>
            <value>
                <fullName>Palermo - Photo Production</fullName>
                <isActive>false</isActive>
                <label>Palermo - Photo Production</label>
            </value>
            <value>
                <fullName>Origins</fullName>
                <isActive>false</isActive>
                <label>Retouching - Origins</label>
            </value>
            <value>
                <fullName>Social Content</fullName>
                <isActive>false</isActive>
                <label>Social Content</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opp_Primary Contact (PrimaryContact__c) is a lookup field linking an Opportunity to its main Contact. It helps track key decision-makers, improve reporting, and enable automation. Used for CRM insights, sales follow-ups, and potential process automation. Ensure it&apos;s populated for accurate reporting and workflow triggers.</description>
    <label>Primary Contact (Opp)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities-Primary Contact</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Is_Template__c.field-meta.xml
<CustomField>
    <fullName>Is_Template__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Field is used to specify that a quote is set up as a template for auto quote generation. (AutoQuoteGeneration Apex class) Auto Quote Generation works for all new opportunities created and generates a quote based on the Service Type using 3x Methods. If previous won opportunity for the account with the same service type exists, it clones the primary quote from this previous opportunity. If there isn&apos;t a previous won opportunities, it checks to see whether the account has an account level template quote for this service type. If not, it uses our Company Level template quote for this service type. The mindset is that quotes from previously won opportunities for an account are the most up to date quotes and our company wide template quotes need most manual adjustments so these are considered as last step.</description>
    <inlineHelpText>This Field is used to specify that a quote is set up as a template for auto quote generation. (AutoQuoteGeneration Apex class) Auto Quote Generation works for all new opportunities created and generates a quote based on the Service Type using 3x Methods. If previous won opportunity for the account with the same service type exists, it clones the primary quote from this previous opportunity. If there isn&apos;t a previous won opportunities, it checks to see whether the account has an account level template quot</inlineHelpText>
    <label>Is Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <description>This Field is used to specify Service Type when a quote is being set up as a template for auto quote generation. (AutoQuoteGeneration Apex class) Auto Quote Generation works for all new opportunities created and generates a quote based on the Service Type using 3x Methods. If previous won opportunity for the account with the same service type exists, it clones the primary quote from this previous opportunity. If there isn&apos;t a previous won opportunities, it checks to see whether the account has an account</description>
    <inlineHelpText>This Field is used to specify Service Type when a quote is being set up as a template for auto quote generation. (AutoQuoteGeneration Apex class) Auto Quote Generation works for all new opportunities created and generates a quote based on the Service Type using 3x Methods. If previous won opportunity for the account with the same service type exists, it clones the primary quote from this previous opportunity. If there isn&apos;t a previous won opportunities, it checks to see whether the account has an account</inlineHelpText>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__PriceBook__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price Book associated with this Quote.</description>
    <inlineHelpText>Price Book associated with this Quote.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.
A primary quote must be selected for our Reporting/Dashboards to function properly.
The Primary Quote should be the most recent quote and/or the approved final customer quote</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>This relates to the &apos;Days on Project&apos; Field when Editing Quote Lines
Enter the # of Days for the Project Here
This is a Managed Package Field and the Field Name is unable to be revised to &apos;Days on Project&apos; which would be more suited to it&apos;s use in our Organization.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/createQBInvoice_Test.cls
@isTest
public class createQBInvoice_Test {
    
    private static Opportunity createData(String connectTo)
    {
        
        List<PricebookEntry> listofPricebookEntry =  createPricebook();
        
        Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        Account slate = new Account(Name = 'Slate Studios',RecordTypeId = rtId);
        Account client = new Account(Name = 'Client Account',RecordTypeId = rtId);
        insert new List<Account>{slate,client};
        
        Contact c = new Contact(FirstName = 'Test', LastName = 'Con', Email = 'testcon@test.com', AccountId = client.Id);
        insert c;
        
        SBQQ__Quote__c qu;
        
        if(connectTo == null)
            qu = createQuote(slate.Id,null,false);
        else if(connectTo == 'Client')
            qu = createQuote(client.Id,null,true);
            
        Id oppRtId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Opportunity').getRecordTypeId();
        Division__c slateDivision = new Division__c(Name = 'Slate');
        insert slateDivision;
        Opportunity opp = new Opportunity();
        opp.RecordTypeId = oppRtId;
        opp.Name = 'Test';
        opp.AccountId = client.Id;
        opp.Division__c = slateDivision.Id;
        opp.Lead_Producer__c = 'Cameron Krone';
        opp.Lead_Type__c = 'E-Commerce';
        opp.StageName = connectTo == 'Opp' ? 'Closed - Won' : 'Qualification';
        opp.CloseDate = System.today().addMonths(1);
        opp.PrimaryContact__c = c.Id;
        opp.Days__c = 1;
        insert opp;
        
        if(connectTo == 'Opp')
        {
            qu = createQuote(client.Id, opp.Id,true);
        }
        
        return opp;
    }
    
    private static List<PricebookEntry> createPricebook()
    {
        breadwinner_qbo__BW_QB_Item__c  objitem = new breadwinner_qbo__BW_QB_Item__c ();
        objitem.Name = 'test';
        objitem.breadwinner_qbo__Reference_ID__c = 'tetsdt-123';
        insert objitem;

        Product2 p1 = new Product2(Name = 'Photographer', isActive = true, ProductCode = 'PHOTO' ,breadwinner_qbo__QB_Item__c =objitem.id );
        Product2 p2 = new Product2(Name = 'Stylist', isActive = true, ProductCode = 'Style',breadwinner_qbo__QB_Item__c =objitem.id);
        Product2 p3 = new Product2(Name = 'Studio Assistant', isActive = true, ProductCode = 'StdAsst',breadwinner_qbo__QB_Item__c =objitem.id);
        insert new List<Product2>{p1,p2,p3};
        
        Id pbId = Test.getStandardPricebookId();
            
        PricebookEntry pe1 = new PricebookEntry(Product2Id = p1.Id, Pricebook2Id = pbId, UnitPrice = 100, IsActive = true);
        PricebookEntry pe2 = new PricebookEntry(Product2Id = p2.Id, Pricebook2Id = pbId, UnitPrice = 200, IsActive = true);
        PricebookEntry pe3 = new PricebookEntry(Product2Id = p3.Id, Pricebook2Id = pbId, UnitPrice = 300, IsActive = true);
        List<PricebookEntry> listofPricebookEntry = new List<PricebookEntry>();
        listofPricebookEntry.add(pe1);
        listofPricebookEntry.add(pe2);
        listofPricebookEntry.add(pe3);
        insert listofPricebookEntry;
        return listofPricebookEntry;
    }
    
    private static SBQQ__Quote__c createQuote(Id accId, Id oppId, boolean primary)
    {  
        SBQQ__Quote__c qt = new SBQQ__Quote__c();
        qt.SBQQ__Account__c = accId;
        qt.SBQQ__Opportunity2__c = oppId != null ? oppId : null;
        qt.Lead_Type__c = 'E-Commerce';
        qt.Is_Template__c = oppId != null ? false : true;
        qt.SBQQ__PriceBook__c = Test.getStandardPricebookId();
        qt.SBQQ__Primary__c = primary;
        qt.SBQQ__SubscriptionTerm__c = 1;
        insert qt;
        
        List<SBQQ__QuoteLine__c> lines = new List<SBQQ__QuoteLine__c>();
        for(PricebookEntry pe:[SELECT Id, Product2Id, UnitPrice FROM PricebookEntry])
        {
            SBQQ__QuoteLine__c ql = new SBQQ__QuoteLine__c();
            ql.SBQQ__Product__c = pe.Product2Id;
            ql.SBQQ__ListPrice__c = pe.UnitPrice;
            ql.SBQQ__Quote__c = qt.Id;
            lines.add(ql);
        }
        insert lines;
            
        return qt;
    }
    @isTest
    static void testcreateInvoice() {
        Opportunity oppRec = createData('Opp'); 
        breadwinner_qbo__Breadwinner_Account_Connection__c  obj = new breadwinner_qbo__Breadwinner_Account_Connection__c();
        obj.breadwinner_qbo__Salesforce_Account__c =oppRec.AccountId;
        obj.breadwinner_qbo__QBO_Org_Name__c = 'Standard Slate';
        obj.breadwinner_qbo__Reference_Id__c = 'tetsdt-123';
        insert obj;
        Test.startTest();
        try{
            createQBInvoice.createInvoice(oppRec.Id);
        }catch(exception ex){
        }
        createQBInvoice.createInvoiceJSON();
        createQBInvoice.createLineItemList();
        String oppid = CreateUpdateQBInvoiceByUser.CreateUpdateInvoice(oppRec.Id);
        updateInvoiceflow.CreateUpdateInvoice(new List<id>{oppRec.Id});
        Test.stopTest();

        Assert.areEqual(oppRec.Id, oppid);
    }
    @isTest
    static void testupdateInvoice() {
        Opportunity oppRec = createData('Opp'); 
        breadwinner_qbo__Breadwinner_Account_Connection__c  obj = new breadwinner_qbo__Breadwinner_Account_Connection__c();
        obj.breadwinner_qbo__Salesforce_Account__c =oppRec.AccountId;
        obj.breadwinner_qbo__QBO_Org_Name__c = 'Standard Slate';
        obj.breadwinner_qbo__Reference_Id__c = 'tetsdt-123';
        insert obj;
        breadwinner_qbo__Invoice__c invobj = new breadwinner_qbo__Invoice__c();
        invobj.breadwinner_qbo__Invoice_ID__c ='hsjdhfiwe43534tref';
        invobj.breadwinner_qbo__Due_Date__c = System.today().addDays(10);
        invobj.breadwinner_qbo__Opportunity__c  =oppRec.Id;
        invobj.breadwinner_qbo__Sync_Token__c = '0';
        insert invobj;
        Test.startTest();
        try{
            updateQBInvoice.updateInvoice(oppRec.Id);
        }catch(exception ex){
        }
        updateQBInvoice.createInvoiceJSON();
        updateQBInvoice.createLineItemList();
        String oppid = CreateUpdateQBInvoiceByUser.CreateUpdateInvoice(oppRec.Id);
        updateInvoiceflow.CreateUpdateInvoice(new List<id>{oppRec.Id});
        Test.stopTest();

        Assert.areEqual(oppRec.Id, oppid);
    }
    
    @isTest
    static void testCreateCustomer()
    {
        Opportunity oppRec = createData('Opp');
        
        Test.startTest();
        try{
        createQBCustomer.createCustomer(oppRec.Id);
        }catch(Exception e)
        {}
        Test.stopTest();
    }
}