force-app/main/default/objects/Account/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Contact field at Account level may differ from Opportunity level. 
Every Account must have a designated Primary Contact.</description>
    <label>Primary Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Total # of Shoot Days for Opp
Used by Calendar to Lookup Opp Start Date and auto calculate Opp End Date</description>
    <inlineHelpText>Total # of Shoot Days for Opp
Used by Calendar to Lookup Opp Start Date and auto calculate Opp End Date</inlineHelpText>
    <label>Shoot Date - # Days</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Producer__c.field-meta.xml
<CustomField>
    <fullName>Lead_Producer__c</fullName>
    <description>This is a Single Picklist Field to enter the Lead Producer for each Opportunity
This field is important for Reporting Dashboards for Employee Performance and also allows Lead Producers to sort the Opportunity Pipeline Views to show only their assigned Projects.</description>
    <inlineHelpText>This is a Single Picklist Field to enter the Lead Producer for each Opportunity
This field is important for Reporting Dashboards for Employee Performance and also allows Lead Producers to sort the Opportunity Pipeline Views to show only their assigned Projects.</inlineHelpText>
    <label>Lead Producer</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Heather Cullum</fullName>
                <default>true</default>
                <label>Heather Cullum</label>
            </value>
            <value>
                <fullName>Ferhat Yurdam</fullName>
            </value>
            <value>
                <fullName>Cameron Krone</fullName>
            </value>
            <value>
                <fullName>Regina Bakeeva</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <description>Svc Type (Required) – Must be entered when creating an Opp.
Syncs with Auto Quote Builder to generate quotes based on Svc Type.</description>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand Content</fullName>
                <label>Slate - Brand Content</label>
            </value>
            <value>
                <fullName>Slate - CGI</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
                <default>true</default>
                <label>Slate - eCom</label>
            </value>
            <value>
                <fullName>Motion</fullName>
                <label>Slate - Motion</label>
            </value>
            <value>
                <fullName>Retouching</fullName>
                <label>Slate - Retouch</label>
            </value>
            <value>
                <fullName>Studio Rental</fullName>
                <label>Slate - Studio &amp; Eq</label>
            </value>
            <value>
                <fullName>Retouching - Align</fullName>
                <label>Align - Retouch</label>
            </value>
            <value>
                <fullName>Palermo - Branding</fullName>
            </value>
            <value>
                <fullName>Palermo - Video Production</fullName>
                <label>Palermo - Content</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Post Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Post Production</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Production</label>
            </value>
            <value>
                <fullName>Palermo - Photo Production</fullName>
                <isActive>false</isActive>
                <label>Palermo - Photo Production</label>
            </value>
            <value>
                <fullName>Origins</fullName>
                <isActive>false</isActive>
                <label>Retouching - Origins</label>
            </value>
            <value>
                <fullName>Social Content</fullName>
                <isActive>false</isActive>
                <label>Social Content</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Type_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type_Sub_Type__c</fullName>
    <description>Required Field when entering Opp in Gmail Integration Panel.
Included in Opp Name Automation w a &apos;_P&apos; for Product and &apos;_OF&apos; for On Model</description>
    <label>Service, Sub</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Model</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PandaDocGeneratorICATemplateTest.cls
@isTest
public class PandaDocGeneratorICATemplateTest {
    private class Mock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse res = new HTTPResponse();
            if (req.getEndpoint().contains('templates') && req.getMethod() == 'GET') {
                res.setBody('{"results":[{"id":"UgNqHrtsGFqTSk8wtdzqPM","name":"API Sample Document from PandaDoc Template","date_created":"2017-08-06T08:42:13.836022Z","date_modified":"2017-09-04T02:21:13.963750Z","version":"1"}]}');
                res.setStatusCode(200);
            } else if (req.getEndpoint().contains('documents') && req.getMethod() == 'GET') {
                res.setBody('{"results":[{"id":"UgNqHrtsGFqTSk8wtdzqPM","name":"API Sample Document from PandaDoc Template","date_created":"2017-08-06T08:42:13.836022Z","date_modified":"2017-09-04T02:21:13.963750Z","version":"1"}]}');
                res.setStatusCode(200);
            } else if (req.getEndpoint().contains('documents') && req.getMethod() == 'POST') {
                res.setBody('{"id":"UgNqHrtsGFqTSk8wtdzqPM","name":"API Sample Document from PandaDoc Template","date_created":"2017-08-06T08:42:13.836022Z","date_modified":"2017-09-04T02:21:13.963750Z","version":"1"}');
                res.setStatusCode(201);
            } else if (req.getEndpoint().contains('documents') && req.getEndpoint().contains('send') && req.getMethod() == 'POST') {
                res.setBody('{"results":[{"id":"UgNqHrtsGFqTSk8wtdzqPM","name":"API Sample Document from PandaDoc Template","date_created":"2017-08-06T08:42:13.836022Z","date_modified":"2017-09-04T02:21:13.963750Z","version":"1"}]}');
                res.setStatusCode(200);
            }
            return res;
        }
    }
    
    @isTest
    static void pandaDocGeneratorICATemplateTest(){
        Test.setMock(HttpCalloutMock.class, new Mock());
        Account accRec = new Account(Name = 'TestAccount');
        Insert accRec;
        
        Contact conRec = new Contact(FirstName = 'test', LastName = 'Test1', Email='test@testc.om', AccountId = accRec.Id);
        Insert conRec;
        
        Id oppRtId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Opportunity').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.RecordTypeId = oppRtId;
        opp.Name = 'Test';
        opp.AccountId = accRec.Id;
        opp.Lead_Producer__c = 'Cameron Krone';
        opp.Lead_Type__c = 'E-Commerce';
        opp.Service_Type_Sub_Type__c = 'Product';
        opp.StageName =  'Closed - Won';
        opp.CloseDate = System.today().addMonths(1);
        opp.Days__c = 1;
        insert opp;
        
        CallSheet__c callSheetRec = new CallSheet__c(Name = 'Test1', Opportunity__c = opp.Id);
        Insert callSheetRec;
        
        Call_Sheet_Prospect__c callProspect = new Call_Sheet_Prospect__c(Call_Sheet__c = callSheetRec.Id, Contact__c = conRec.Id);
        Insert callProspect;
        
        Test.startTest();
        PandaDocGeneratorICATemplate.getTemplateList();
        PandaDocGeneratorICATemplate.getDocumentList('test');
        PandaDocGeneratorICATemplate.getContactName(conRec.Id);
        PandaDocGeneratorICATemplate.getOpportunityName(callSheetRec.Id);
        PandaDocGeneratorICATemplate.createICAPandaDoc(conRec.Id);
        PandaDocGeneratorICATemplate.createCallSheetDocument(callSheetRec.Id);
        PandaDocGeneratorICATemplate.sendDocument('docId');
        Test.stopTest();
    }
}