force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.
A primary quote must be selected for our Reporting/Dashboards to function properly.
The Primary Quote should be the most recent quote and/or the approved final customer quote</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CloneQuoteFlowController.cls
public class CloneQuoteFlowController {
    @AuraEnabled public String oldRecordId {get;set;}
    @AuraEnabled public String newRecordId {get;set;}
    
    public CloneQuoteFlowController(ApexPages.StandardController stdController) {
        this.oldRecordId = stdController.getId();
    }

    public Pagereference cloneQuote(){
        Map<String, Object> params = new Map<String, Object>();
        params.put('recordId', oldRecordId);
        Flow.Interview.Clone_Quotes_Exactly cloneFlow = new Flow.Interview.Clone_Quotes_Exactly(params);
        cloneFlow.start();
        newRecordId = (string) cloneFlow.getvariableValue('New_Quote_Id');
        SBQQ__Quote__c newQuote = [SELECT Id, SBQQ__Primary__c FROM SBQQ__Quote__c WHERE Id = :newRecordId];
        if(!newQuote.SBQQ__Primary__c){
            newQuote.SBQQ__Primary__c = true;
            update newQuote;
        }
        PageReference pg = new PageReference('/'+newRecordId);
        pg.setRedirect(true);
        return pg; 
    }
}