force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <description>This Field is used to specify Service Type when a quote is being set up as a template for auto quote generation. (AutoQuoteGeneration Apex class) Auto Quote Generation works for all new opportunities created and generates a quote based on the Service Type using 3x Methods. If previous won opportunity for the account with the same service type exists, it clones the primary quote from this previous opportunity. If there isn&apos;t a previous won opportunities, it checks to see whether the account has an account</description>
    <inlineHelpText>This Field is used to specify Service Type when a quote is being set up as a template for auto quote generation. (AutoQuoteGeneration Apex class) Auto Quote Generation works for all new opportunities created and generates a quote based on the Service Type using 3x Methods. If previous won opportunity for the account with the same service type exists, it clones the primary quote from this previous opportunity. If there isn&apos;t a previous won opportunities, it checks to see whether the account has an account</inlineHelpText>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/handlers/QuoteLineItemTriggerHandler.cls
public class QuoteLineItemTriggerHandler {
    
    public static void handleAfterInsert(List<SBQQ__QuoteLine__c> lineItems){
        List<SBQQ__QuoteLine__c> lineItemsWithContact = new List<SBQQ__QuoteLine__c>();
        for(SBQQ__QuoteLine__c lineItem : lineItems){
            if(lineItem.Vendor__c != null){
                lineItemsWithContact.add(lineItem);
            }
        }
        if(!lineItemsWithContact.IsEmpty()){
			handleOcrCreation(lineItemsWithContact);            
        }
    }
    
    public static void handleAfterUpdate(List<SBQQ__QuoteLine__c> newList, Map<Id,SBQQ__QuoteLine__c> oldMap){
        List<SBQQ__QuoteLine__c> lineItemsWithContact = new List<SBQQ__QuoteLine__c>();
        for(SBQQ__QuoteLine__c lineItem : newList){
            SBQQ__QuoteLine__c oldItem = oldMap.get(lineItem.Id);
            if(lineItem.Vendor__c != null && oldItem.Vendor__c != lineItem.Vendor__c){
                lineItemsWithContact.add(lineItem);
            }
        }
        if(!lineItemsWithContact.IsEmpty()){
			handleOcrCreation(lineItemsWithContact);            
        }
    }
    
    public static void handleOcrCreation(List<SBQQ__QuoteLine__c> lineItems){
        Set<Id> opportunityIds = new Set<Id>();
        Set<Id> vendorIds = new Set<Id>();
        Map<Id, Id> quoteToOpportunityMap = new Map<Id, Id>();
        List<OpportunityContactRole> rolesToInsert = new List<OpportunityContactRole>();
        
        for (SBQQ__QuoteLine__c quoteLine : lineItems) {
            if (quoteLine.Vendor__c != null && quoteLine.SBQQ__Quote__c != null) {
                opportunityIds.add(quoteLine.SBQQ__Quote__c);
                vendorIds.add(quoteLine.Vendor__c);
            }
        }
        
        if (!opportunityIds.isEmpty()) {
            for (SBQQ__Quote__c quote : [
                SELECT Id, SBQQ__Opportunity2__c FROM SBQQ__Quote__c 
                WHERE Id IN :opportunityIds
            ]) {
                quoteToOpportunityMap.put(quote.Id, quote.SBQQ__Opportunity2__c);
            }
        }
        
        for (SBQQ__QuoteLine__c quoteLine : lineItems) {
            Id opportunityId = quoteToOpportunityMap.get(quoteLine.SBQQ__Quote__c);
            
            OpportunityContactRole newRole = new OpportunityContactRole(
                OpportunityId = opportunityId,
                ContactId = quoteLine.Vendor__c,
                Role = quoteLine.Lead_Type__c
            );
            rolesToInsert.add(newRole);
        }
        if (!rolesToInsert.isEmpty()) {
            insert rolesToInsert;
        }
    }
    
}