force-app/main/default/objects/Opportunity/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <description>Copy &amp; Paste Initial Client Inquiry Email into this field. 
Required Field upon Opp Creation in Gmail Integration
Have considered automating this w Einstein Gmail integration into Activity section, however, initial email would become buried at bottom of activity chain unless we determined best practice for &apos;pinning&apos; initial email to top. 
Starting 12/2022, Typeform now auto-populates field based on Typeform responses</description>
    <inlineHelpText>Copy &amp; Paste Initial Client Inquiry Email into this field. 
Required Field upon Opp Creation in Gmail Integration
Have considered automating this w Einstein Gmail integration into Activity section, however, initial email would become buried at bottom of activity chain unless we determined best practice for &apos;pinning&apos; initial email to top. 
Starting 12/2022, Typeform now auto-populates field based on Typeform responses</inlineHelpText>
    <label>Initial Inquiry</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Before_After_Link__c.field-meta.xml
<CustomField>
    <fullName>Before_After_Link__c</fullName>
    <label>zTypeform - Before &amp; After</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Image_Count__c.field-meta.xml
<CustomField>
    <fullName>Image_Count__c</fullName>
    <description>Total Image Count for the Opp
Used in Account Level reporting + good standard of Opp &apos;Size&apos;
Price Per Image Calculation is based on Image Count entered into this Field</description>
    <label>Image Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Images_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Images_Monthly__c</fullName>
    <label>zTypeform - Image Month</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <description>Svc Type (Required) – Must be entered when creating an Opp.
Syncs with Auto Quote Builder to generate quotes based on Svc Type.</description>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand Content</fullName>
                <label>Slate - Brand Content</label>
            </value>
            <value>
                <fullName>Slate - CGI</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
                <default>true</default>
                <label>Slate - eCom</label>
            </value>
            <value>
                <fullName>Motion</fullName>
                <label>Slate - Motion</label>
            </value>
            <value>
                <fullName>Retouching</fullName>
                <label>Slate - Retouch</label>
            </value>
            <value>
                <fullName>Studio Rental</fullName>
                <label>Slate - Studio &amp; Eq</label>
            </value>
            <value>
                <fullName>Retouching - Align</fullName>
                <label>Align - Retouch</label>
            </value>
            <value>
                <fullName>Palermo - Branding</fullName>
            </value>
            <value>
                <fullName>Palermo - Video Production</fullName>
                <label>Palermo - Content</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Post Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Post Production</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Production</label>
            </value>
            <value>
                <fullName>Palermo - Photo Production</fullName>
                <isActive>false</isActive>
                <label>Palermo - Photo Production</label>
            </value>
            <value>
                <fullName>Origins</fullName>
                <isActive>false</isActive>
                <label>Retouching - Origins</label>
            </value>
            <value>
                <fullName>Social Content</fullName>
                <isActive>false</isActive>
                <label>Social Content</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Descriptor__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Descriptor__c</fullName>
    <description>This is an Additional Description of the Opportunity.
The Opportunity Name has a Standard 30 Character Limit due to Quickbooks Charactor Limitations
Because of this, additional information beyond the Initial Lead Date, Account Name, and Service Type should be entered here.

For Example: Fall/Winter Collection</description>
    <inlineHelpText>This is an Additional Description of the Opportunity.
The Opportunity Name has a Standard 30 Character Limit due to Quickbooks Charactor Limitations
Because of this, additional information beyond the Initial Lead Date, Account Name, and Service Type should be entered here.

For Example: Fall/Winter Collection</inlineHelpText>
    <label>Opportunity Descriptor</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pain_Points__c.field-meta.xml
<CustomField>
    <fullName>Pain_Points__c</fullName>
    <label>zTypeform - Pain Point</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Post_Production_Method__c.field-meta.xml
<CustomField>
    <fullName>Post_Production_Method__c</fullName>
    <label>zTypeform - Post Method</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opp_Primary Contact (PrimaryContact__c) is a lookup field linking an Opportunity to its main Contact. It helps track key decision-makers, improve reporting, and enable automation. Used for CRM insights, sales follow-ups, and potential process automation. Ensure it&apos;s populated for accurate reporting and workflow triggers.</description>
    <label>Primary Contact (Opp)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities-Primary Contact</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Budget__c.field-meta.xml
<CustomField>
    <fullName>Project_Budget__c</fullName>
    <label>zTypeform - Budget</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Project_Deadline__c</fullName>
    <label>zTypeform - Deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Start_Date__c</fullName>
    <label>zTypeform - Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Service_of_Interest__c</fullName>
    <label>zTypeform - Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Description</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Services_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Services_of_Interest__c</fullName>
    <label>zService Type - Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Services_of_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadConvertController.cls
public class LeadConvertController {
    private static Lead toConvert;
    private static Map<String, String> palermoServiceType;
    private static Map<String, String> alignServiceType;
    private static Map<String, String> slateServiceType;
    
    public static void convertLeads(Id leadId)
    {
        List<Lead> qryRslt = (List<Lead>)Database.query(createQuery());
       	toConvert = qryRslt[0];
        
        Opportunity opp = createOpportunity();
        
        List<Account> existingAccs = [SELECT Id, Name FROM Account WHERE Name =: toConvert.company LIMIT 1];
        List<Contact> existingCon = [SELECT Id, Name, Email, AccountId FROM Contact WHERE Email =: toConvert.email LIMIT 1];
        
        Savepoint tisGood = Database.setSavepoint();
        
        try{
            Id existingAcc;
        	Database.LeadConvert lc = new Database.LeadConvert();
        	lc.setLeadId(toConvert.Id);
        	lc.setDoNotCreateOpportunity(true);
            
            if(!existingAccs.isEmpty())
            {
                existingAcc = existingAccs[0].Id;
                lc.setAccountId(existingAcc);
            }
            
            if(!existingCon.isEmpty() && existingAcc != null)
            {
                if(existingCon[0].AccountId == existingAcc)
                	lc.setContactId(existingCon[0].Id);
            }
            
            LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
			lc.setConvertedStatus(convertStatus.MasterLabel);
            
            Database.LeadConvertResult lcr = Database.convertLead(lc);

            if(!lcr.isSuccess())
            	throw new leadConvertException(lcr.getErrors()[0].getMessage());
			else
            {
                opp.AccountId = lcr.getAccountId();
                opp.PrimaryContact__c = lcr.getContactId();
                insert opp;
            }
        }catch(Exception e){
            System.debug(e.getMessage());
            System.debug(e.getStackTraceString());
            Database.rollback(tisGood);
        }
        
    }
    
    private static Opportunity createOpportunity()
    {
        createServiceTypeMapping();
        
        Opportunity opp = new Opportunity();
        opp.Name = toConvert.Company;
        opp.Project_Budget__c =  toConvert.Project_Budget__c;
        opp.Service_of_Interest__c = toConvert.Service_of_Interest__c;
        opp.Services_of_Interest__c = toConvert.Services_of_Interest__c;
        opp.Additional_Info__c = toConvert.Project_Brief__c;
        opp.Project_Start_Date__c = toConvert.Project_Start_Date__c;
        opp.Project_Deadline__c = toConvert.Project_Deadline__c;
        opp.Project_Budget__c = toConvert.Project_Budget__c;
        opp.CloseDate = toConvert.Project_Start_Date__c != null ? toConvert.Project_Start_Date__c.addMonths(1).toStartofMonth().addDays(-1) : System.today().addMonths(1).toStartofMonth().addDays(-1);
        opp.Image_Count__c = toConvert.Image_Count__c;
        opp.Images_Monthly__c = toConvert.Image_Count_Monthly__c;
        opp.Before_After_Link__c = toConvert.Before_After_Link__c;
        opp.Post_Production_Method__c = toConvert.Post_Production_Method__c;
        Opp.Pain_Points__c = toConvert.Pain_Points__c;
        opp.LeadSource = String.isNotEmpty(toConvert.LeadSource) && toConvert.LeadSource.containsIgnoreCase('Mailing List') ? 'Email - Newsletter' : toConvert.LeadSource;
        opp.StageName = (!String.isBlank(toConvert.Services_of_Interest__c) && toConvert.Services_of_Interest__c.containsIgnoreCase('General Inquiry')) ? 'Qualification - General Inquiry' : 'Qualification - Specific Project';
        opp.Lead_Type__c = getLeadType(opp.Service_of_Interest__c);
        
        if(toConvert.Inquiry_For__c == 'Palermo')
        	opp.Opportunity_Descriptor__c = 'Palermo - ' + opp.Service_of_Interest__c;
        if(toConvert.Inquiry_For__c == 'Align')
        {
            if(opp.Image_Count__c != null)
                opp.Opportunity_Descriptor__c = 'Align - ' + String.valueOf((Integer)opp.Image_Count__c) + 'x Images - TBD';
            else
                opp.Opportunity_Descriptor__c = 'Align - TBD';
        }
        if(toConvert.Inquiry_For__c == 'Slate')
            opp.Opportunity_Descriptor__c = 'Slate - ' + opp.Service_of_Interest__c;
        
        
        
        return opp;
    }
    
    private static String createQuery()
    {
        String query = 'SELECT Id, ';
        
        List<Schema.FieldSetMember> flds = SObjectType.Lead.FieldSets.Typeform_Lead_Convert.getFields();
        
        for(Schema.FieldSetMember fld:flds)
        {
            query += fld.getFieldPath() + ', ';
        }
        
        query = query.removeEnd(', ');
        query += ' FROM Lead WHERE Id =: leadId';
		system.debug(query);        
        return query;
    }
    
    private static String getLeadType(String selectedService)
    {
        //Start Service Type logic
        String LeadType;
        
        if(toConvert.Inquiry_For__c == 'Palermo')
            LeadType = palermoServiceType.get(selectedService);
        else if(toConvert.Inquiry_For__c == 'Align')
            LeadType = alignServiceType.get(selectedService);
        else if(toConvert.Inquiry_For__c == 'Slate')
            LeadType = slateServiceType.get(selectedService);
        
        return LeadType;
    }
    
    private static void createServiceTypeMapping()
    {
        palermoServiceType = new Map<String,String>();
        palermoServiceType.put('Art Direction & Strategy','Palermo - Branding');
        palermoServiceType.put('Branding & Identity','Palermo - Video Production');
        palermoServiceType.put('Content Production','Palermo - E-Commerce Content Production');
        palermoServiceType.put('Digital/UX','Palermo - Digital/UX');
        palermoServiceType.put('CGI','Palermo - CGI');
        
        alignServiceType = new Map<String,String>();
        alignServiceType.put('CGI','Align - CGI');
        alignServiceType.put('Retouching','Retouching - Align');
        alignServiceType.put('Video Editing','Align - Video Editing');
        alignServiceType.put('VFX/Animation','Align - VFX/Animation');
        
        slateServiceType = new Map<String,String>();
        slateServiceType.put('Brand Content Production','Brand Content');
        slateServiceType.put('CGI Content Production', 'Slate - CGI');
        slateServiceType.put('E-Commerce Content Production', 'E-Commerce');
        slateServiceType.put('Motion Content Production', 'Motion');
        slateServiceType.put('Retouching', 'Retouching');
        slateServiceType.put('Studio & Equipment Rental', 'Studio Rental');
    }
    
    public class leadConvertException extends Exception{}
}