force-app/main/default/objects/Opportunity/fields/Continuous__c.field-meta.xml
<CustomField>
    <fullName>Continuous__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If no gap in shoot dates, check Continuous
If gaps in shoot dates, uncheck Continuous</inlineHelpText>
    <label>Shoot Date - Continuous Dates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Hold_1__c.field-meta.xml
<CustomField>
    <fullName>First_Hold_1__c</fullName>
    <description>Located in Gmail Integration for Opp Creation.
Eenter 1st Option Start Dates here.
Integrates w Shoot Holds Calendar. 
Warning to inform of conflicting Holds in calendar to reduce error.</description>
    <inlineHelpText>Located in Gmail Integration for Opp Creation.
Eenter 1st Option Start Dates here.
Integrates w Shoot Holds Calendar. 
Warning to inform of conflicting Holds in calendar to reduce error.</inlineHelpText>
    <label>Shoot Date - 1st - Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Hold_2__c.field-meta.xml
<CustomField>
    <fullName>First_Hold_2__c</fullName>
    <description>In Gmail Integration for Opp Creation.
Enter 1st Option End Dates here.
Integrates w Shoot Holds Calendar. 
Warning to inform of conflicting Holds in the calendar to reduce error.</description>
    <inlineHelpText>In Gmail Integration for Opp Creation.
Enter 1st Option End Dates here.
Integrates w Shoot Holds Calendar. 
Warning to inform of conflicting Holds in the calendar to reduce error.</inlineHelpText>
    <label>Shoot Date - 1st - End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Producer__c.field-meta.xml
<CustomField>
    <fullName>Lead_Producer__c</fullName>
    <description>This is a Single Picklist Field to enter the Lead Producer for each Opportunity
This field is important for Reporting Dashboards for Employee Performance and also allows Lead Producers to sort the Opportunity Pipeline Views to show only their assigned Projects.</description>
    <inlineHelpText>This is a Single Picklist Field to enter the Lead Producer for each Opportunity
This field is important for Reporting Dashboards for Employee Performance and also allows Lead Producers to sort the Opportunity Pipeline Views to show only their assigned Projects.</inlineHelpText>
    <label>Lead Producer</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Heather Cullum</fullName>
                <default>true</default>
                <label>Heather Cullum</label>
            </value>
            <value>
                <fullName>Ferhat Yurdam</fullName>
            </value>
            <value>
                <fullName>Cameron Krone</fullName>
            </value>
            <value>
                <fullName>Regina Bakeeva</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Producer_Email__c.field-meta.xml
<CustomField>
    <fullName>Lead_Producer_Email__c</fullName>
    <description>This is a Lookup Field to the Lead Producer Field which auto populates based on the Lead Producer assigned
This field is important for Round Robin automations as the Round Robin emails from the Email Address of the Lead Producer on the Opportunity; not on the Creator of the Opportunity</description>
    <inlineHelpText>This is a Lookup Field to the Lead Producer Field which auto populates based on the Lead Producer assigned
This field is important for Round Robin automations as the Round Robin emails from the Email Address of the Lead Producer on the Opportunity; not on the Creator of the Opportunity</inlineHelpText>
    <label>Lead Producer Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <description>Svc Type (Required) – Must be entered when creating an Opp.
Syncs with Auto Quote Builder to generate quotes based on Svc Type.</description>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand Content</fullName>
                <label>Slate - Brand Content</label>
            </value>
            <value>
                <fullName>Slate - CGI</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
                <default>true</default>
                <label>Slate - eCom</label>
            </value>
            <value>
                <fullName>Motion</fullName>
                <label>Slate - Motion</label>
            </value>
            <value>
                <fullName>Retouching</fullName>
                <label>Slate - Retouch</label>
            </value>
            <value>
                <fullName>Studio Rental</fullName>
                <label>Slate - Studio &amp; Eq</label>
            </value>
            <value>
                <fullName>Retouching - Align</fullName>
                <label>Align - Retouch</label>
            </value>
            <value>
                <fullName>Palermo - Branding</fullName>
            </value>
            <value>
                <fullName>Palermo - Video Production</fullName>
                <label>Palermo - Content</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Post Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Post Production</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Production</label>
            </value>
            <value>
                <fullName>Palermo - Photo Production</fullName>
                <isActive>false</isActive>
                <label>Palermo - Photo Production</label>
            </value>
            <value>
                <fullName>Origins</fullName>
                <isActive>false</isActive>
                <label>Retouching - Origins</label>
            </value>
            <value>
                <fullName>Social Content</fullName>
                <isActive>false</isActive>
                <label>Social Content</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shoot_Date_2__c.field-meta.xml
<CustomField>
    <fullName>Shoot_Date_2__c</fullName>
    <description>End Date of Opp
Displayed on Opp Page View as Confirmed Shoot Date.
Fows into SF Shoot Date Calendar + issues warnings when entering in conflicting opp dates on opp creation</description>
    <inlineHelpText>End Date of Opp
Displayed on Opp Page View as Confirmed Shoot Date.
Fows into SF Shoot Date Calendar + issues warnings when entering in conflicting opp dates on opp creation</inlineHelpText>
    <label>Shoot Date - End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shoot_Date__c.field-meta.xml
<CustomField>
    <fullName>Shoot_Date__c</fullName>
    <description>Start Date of Opportunity.
Displayed on Opp Page View as Confirmed Shoot Date.
Flows into SF Shoot Date Calendar + issues warnings when entering in conflicting opp dates on opp creation</description>
    <inlineHelpText>Start Date of Opportunity.
Displayed on Opp Page View as Confirmed Shoot Date.
Flows into SF Shoot Date Calendar + issues warnings when entering in conflicting opp dates on opp creation</inlineHelpText>
    <label>Shoot Date - Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shoot_Hold_1__c.field-meta.xml
<CustomField>
    <fullName>Shoot_Hold_1__c</fullName>
    <description>Field located in Gmail Integration for Opp Creation.
Lead Producers enter 2nd Option Start Dates here.
Integrates w Shoot Holds Calendar. 
Warnings for conflicting Holds in calendar to reduce margin of error.</description>
    <inlineHelpText>Field located in Gmail Integration for Opp Creation.
Lead Producers enter 2nd Option Start Dates here.
Integrates w Shoot Holds Calendar. 
Warnings for conflicting Holds in calendar to reduce margin of error.</inlineHelpText>
    <label>Shoot Date - 2nd - Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shoot_Hold_2__c.field-meta.xml
<CustomField>
    <fullName>Shoot_Hold_2__c</fullName>
    <description>Located in Gmail Integration for Opp Creation.
Enter 2nd Option End Dates here.
Integrates w Shoot Holds Calendar. 
Warning to inform of conflicting Holds in calendar to reduce error.</description>
    <inlineHelpText>Located in Gmail Integration for Opp Creation.
Enter 2nd Option End Dates here.
Integrates w Shoot Holds Calendar. 
Warning to inform of conflicting Holds in calendar to reduce error.</inlineHelpText>
    <label>Shoot Date - 2nd - End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Studio_OppTrg_Test.cls
@isTest
public class Studio_OppTrg_Test {

    static testmethod void method1(){
		Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        
        Opportunity opp1 = new Opportunity();
        opp1.Name = 'TestOpp1';
        opp1.StageName = 'Qualification';
        opp1.CloseDate = system.today().addDays(10);
        opp1.AccountId = acc.Id;
        opp1.Lead_Producer__c = 'Cameron Krone';
        opp1.Lead_Producer_Email__c = 'test@produceremail.com';
        opp1.Lead_Type__c = 'Slate - CGI';
        opp1.First_Hold_1__c = Date.newInstance(2022, 01, 25);
        opp1.First_Hold_2__c = Date.newInstance(2022, 01, 27);
        insert opp1;
        
        OpportunityTriggerHandler.ToCreateCalendarRecord = true;
        opp1.Continuous__c = false;
        opp1.Shoot_Hold_1__c = Date.newInstance(2022, 01, 28);
        opp1.Shoot_Hold_2__c = Date.newInstance(2022, 01, 30);
        update opp1;
        
        OpportunityTriggerHandler.ToCreateCalendarRecord = true;
        opp1.Shoot_Date__c = Date.newInstance(2022, 01, 28);
        opp1.Shoot_Date_2__c = Date.newInstance(2022, 01, 30);
        update opp1;
        
        Opportunity opp2 = new Opportunity();
        opp2.Name = 'TestOpp2';
        opp2.StageName = 'Qualification';
        opp2.CloseDate = system.today().addDays(10);
        opp2.AccountId = acc.Id;
        opp2.Lead_Producer__c = 'Cameron Krone';
        opp2.Lead_Producer_Email__c = 'test@produceremail.com';
        opp2.Lead_Type__c = 'E-Commerce';
        opp2.Continuous__c = false;
        opp2.First_Hold_1__c = Date.newInstance(2022, 01, 01);
        opp2.First_Hold_2__c = Date.newInstance(2022, 01, 02);
        opp2.Shoot_Hold_1__c = Date.newInstance(2022, 01, 03);
        opp2.Shoot_Hold_2__c = Date.newInstance(2022, 01, 04);
        OpportunityTriggerHandler.ToCreateCalendarRecord = true;
        insert opp2;
        
        OpportunityTriggerHandler.ToCreateCalendarRecord = true;
        opp2.First_Hold_1__c = null;
        opp2.First_Hold_2__c = null;
        opp2.Shoot_Hold_1__c = null;
        opp2.Shoot_Hold_2__c = null;
        update opp2;
        
        
        System.debug('Error '+[SELECT id,Component_Name__c, Component_Type__c, Error_Message__c, Error_Type__c, Record_Reference__c, Response_Request__c, CreatedDate from Error_Log__c]);
        
    }
    
    static testmethod void method2(){
		Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        
        Opportunity opp1 = new Opportunity();
        opp1.Name = 'TestOpp1';
        opp1.StageName = 'Qualification';
        opp1.CloseDate = system.today().addDays(10);
        opp1.AccountId = acc.Id;
        opp1.Lead_Producer__c = 'Cameron Krone';
        opp1.Lead_Producer_Email__c = 'test@produceremail.com';
        opp1.Lead_Type__c = 'Brand Content';
        opp1.First_Hold_1__c = Date.newInstance(2022, 01, 25);
        opp1.First_Hold_2__c = Date.newInstance(2022, 01, 27);
        insert opp1;
        
        Test.startTest();
        
        opp1.Lead_Type__c = 'Palermo - Digital/UX';
        update opp1;
        
      	Test.stopTest();
    }
    
    static testmethod void method3(){
		Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        
        Opportunity opp1 = new Opportunity();
        opp1.Name = 'TestOpp1';
        opp1.StageName = 'Qualification';
        opp1.CloseDate = system.today().addDays(10);
        opp1.AccountId = acc.Id;
        opp1.Lead_Producer__c = 'Cameron Krone';
        opp1.Lead_Producer_Email__c = 'test@produceremail.com';
        opp1.Lead_Type__c = 'Palermo - Branding';
        opp1.First_Hold_1__c = Date.newInstance(2022, 01, 25);
        opp1.First_Hold_2__c = Date.newInstance(2022, 01, 27);
        insert opp1;
        
        Test.startTest();
        
        opp1.Lead_Type__c = 'Palermo - CGI';
        update opp1;
        
      	Test.stopTest();
    }
}