force-app/main/default/objects/Opportunity/fields/Division_Name__c.field-meta.xml
<CustomField>
    <fullName>Division_Name__c</fullName>
    <inlineHelpText>The name of the Division for which this Opportunity was created</inlineHelpText>
    <label>Division Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Division_Name__c.field-meta.xml
<CustomField>
    <fullName>Division_Name__c</fullName>
    <inlineHelpText>Automatically pulled from Opportunity on creation</inlineHelpText>
    <label>Division Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/handlers/QuoteTriggerHandler.cls
public class QuoteTriggerHandler {

  public static void setDivisionName(List<SBQQ__Quote__c> quotes) {
    Set<Id> opportunityIds = new Set<Id>();
    for (SBQQ__Quote__c quote : quotes) {
      if (quote.SBQQ__Opportunity2__c != null) {
        opportunityIds.add(quote.SBQQ__Opportunity2__c);
      }
    }
    Map<Id, Opportunity> opportunities = new Map<Id, Opportunity>(
      [SELECT Id, Division_Name__c FROM Opportunity WHERE Id IN :opportunityIds]
    );
    for (SBQQ__Quote__c quote : quotes) {
      if (
        quote.SBQQ__Opportunity2__c != null &&
        opportunities.containsKey(quote.SBQQ__Opportunity2__c)
      ) {
        quote.Division_Name__c = opportunities.get(quote.SBQQ__Opportunity2__c)
          .Division_Name__c;
      }
    }
  }
}