force-app/main/default/objects/Opportunity/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <description>Svc Type (Required) – Must be entered when creating an Opp.
Syncs with Auto Quote Builder to generate quotes based on Svc Type.</description>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand Content</fullName>
                <label>Slate - Brand Content</label>
            </value>
            <value>
                <fullName>Slate - CGI</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
                <default>true</default>
                <label>Slate - eCom</label>
            </value>
            <value>
                <fullName>Motion</fullName>
                <label>Slate - Motion</label>
            </value>
            <value>
                <fullName>Retouching</fullName>
                <label>Slate - Retouch</label>
            </value>
            <value>
                <fullName>Studio Rental</fullName>
                <label>Slate - Studio &amp; Eq</label>
            </value>
            <value>
                <fullName>Retouching - Align</fullName>
                <label>Align - Retouch</label>
            </value>
            <value>
                <fullName>Palermo - Branding</fullName>
            </value>
            <value>
                <fullName>Palermo - Video Production</fullName>
                <label>Palermo - Content</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Post Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Post Production</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Production</label>
            </value>
            <value>
                <fullName>Palermo - Photo Production</fullName>
                <isActive>false</isActive>
                <label>Palermo - Photo Production</label>
            </value>
            <value>
                <fullName>Origins</fullName>
                <isActive>false</isActive>
                <label>Retouching - Origins</label>
            </value>
            <value>
                <fullName>Social Content</fullName>
                <isActive>false</isActive>
                <label>Social Content</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Descriptor__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Descriptor__c</fullName>
    <description>This is an Additional Description of the Opportunity.
The Opportunity Name has a Standard 30 Character Limit due to Quickbooks Charactor Limitations
Because of this, additional information beyond the Initial Lead Date, Account Name, and Service Type should be entered here.

For Example: Fall/Winter Collection</description>
    <inlineHelpText>This is an Additional Description of the Opportunity.
The Opportunity Name has a Standard 30 Character Limit due to Quickbooks Charactor Limitations
Because of this, additional information beyond the Initial Lead Date, Account Name, and Service Type should be entered here.

For Example: Fall/Winter Collection</inlineHelpText>
    <label>Opportunity Descriptor</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Budget__c.field-meta.xml
<CustomField>
    <fullName>Project_Budget__c</fullName>
    <label>zTypeform - Budget</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Project_Deadline__c</fullName>
    <label>zTypeform - Deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Start_Date__c</fullName>
    <label>zTypeform - Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Service_of_Interest__c</fullName>
    <label>zTypeform - Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Description</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Services_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Services_of_Interest__c</fullName>
    <label>zService Type - Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Services_of_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadConvertControllerTest.cls
@isTest
public class LeadConvertControllerTest 
{
	static testMethod void testPalermo()
    {
        Lead newLead = new Lead();
        newLead.Company = 'Test Company';
        newLead.FirstName = 'Test';
        newLead.LastName = 'Person';
        newLead.Email = 'what@whatever.com';
        newLead.Services_of_Interest__c = 'Graphic Design;Print Design;Typography';
        newLead.Service_of_Interest__c = 'Branding & Identity';
        newLead.Project_Brief__c = 'This is a project brief.';
        newLead.Project_Start_Date__c = system.today().addDays(2);
        newLead.Project_Deadline__c = system.today().addDays(5);
        newLead.Project_Budget__c = '$20,000 - $25,000';
        newLead.LeadSource = 'Mailing List';
        newLead.isTypeForm__c = true;
        newLead.Inquiry_For__c = 'Palermo';
        insert newLead;
        
        Test.startTest();
        
        Database.executeBatch(new TypeformLeadConvert_Batch(), 1);
        
        Test.stopTest();
        
        Opportunity opp = [SELECT Id, Name, Lead_Type__c, Opportunity_Descriptor__c FROM Opportunity LIMIT 1];
    }
}