force-app/main/default/objects/Opportunity/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <description>Svc Type (Required) – Must be entered when creating an Opp.
Syncs with Auto Quote Builder to generate quotes based on Svc Type.</description>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand Content</fullName>
                <label>Slate - Brand Content</label>
            </value>
            <value>
                <fullName>Slate - CGI</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
                <default>true</default>
                <label>Slate - eCom</label>
            </value>
            <value>
                <fullName>Motion</fullName>
                <label>Slate - Motion</label>
            </value>
            <value>
                <fullName>Retouching</fullName>
                <label>Slate - Retouch</label>
            </value>
            <value>
                <fullName>Studio Rental</fullName>
                <label>Slate - Studio &amp; Eq</label>
            </value>
            <value>
                <fullName>Retouching - Align</fullName>
                <label>Align - Retouch</label>
            </value>
            <value>
                <fullName>Palermo - Branding</fullName>
            </value>
            <value>
                <fullName>Palermo - Video Production</fullName>
                <label>Palermo - Content</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Post Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Post Production</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Production</label>
            </value>
            <value>
                <fullName>Palermo - Photo Production</fullName>
                <isActive>false</isActive>
                <label>Palermo - Photo Production</label>
            </value>
            <value>
                <fullName>Origins</fullName>
                <isActive>false</isActive>
                <label>Retouching - Origins</label>
            </value>
            <value>
                <fullName>Social Content</fullName>
                <isActive>false</isActive>
                <label>Social Content</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <description>This Field is used to specify Service Type when a quote is being set up as a template for auto quote generation. (AutoQuoteGeneration Apex class) Auto Quote Generation works for all new opportunities created and generates a quote based on the Service Type using 3x Methods. If previous won opportunity for the account with the same service type exists, it clones the primary quote from this previous opportunity. If there isn&apos;t a previous won opportunities, it checks to see whether the account has an account</description>
    <inlineHelpText>This Field is used to specify Service Type when a quote is being set up as a template for auto quote generation. (AutoQuoteGeneration Apex class) Auto Quote Generation works for all new opportunities created and generates a quote based on the Service Type using 3x Methods. If previous won opportunity for the account with the same service type exists, it clones the primary quote from this previous opportunity. If there isn&apos;t a previous won opportunities, it checks to see whether the account has an account</inlineHelpText>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloneQuoteFlowControllerTest.cls
@isTest
private  class CloneQuoteFlowControllerTest {
    @testSetup
    private static void createData(){
        Account testAccount= new Account(name='Test Account',BillingCity='Wilmington');
		insert testAccount;
        Opportunity testOpp = new Opportunity(name='Test Opportunity', 
                                              AccountId=testAccount.Id,
                                              StageName='Prospecting',
                                              closeDate=System.today(),
                                              Lead_Type__c='Slate - CGI');
        insert testOpp;
    }

    @isTest 
    private static void cloneQuoteTest(){
        Test.startTest();
        SBQQ__Quote__c q = [SELECT Id, Name FROM SBQQ__Quote__c LIMIT 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(q);
        CloneQuoteFlowController cqfc = new CloneQuoteFlowController(sc);
        Pagereference pr = cqfc.cloneQuote();
        System.assertNotEquals(null, cqfc.newRecordId);
        Test.stopTest();
    }
}