force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <description>A division of Slate&apos;s business, either &quot;Slate&quot;, &quot;Palermo&quot; or &quot;Align&quot; at time of writing.</description>
    <label>Division</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/CC_Fee_invoice__c.field-meta.xml
<CustomField>
    <fullName>CC_Fee_invoice__c</fullName>
    <description>Calculates the credit card processing fee as 4.5% of the remaining balance on an opportunity.
The formula subtracts the Total Amount Paid (breadwinner_qbo__Total_Amount_Paid__c) from the total amount plus tax (Amount + Tax_to_collect__c), then applies a 4.5% fee to the remaining balance.

This ensures that the processing fee reflects only the unpaid portion of the total amount.</description>
    <formula>(Amount +  Tax_to_collect__c - breadwinner_qbo__Total_Amount_Paid__c) * 0.045</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CC Fee_Inv</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CC_Payment__c.field-meta.xml
<CustomField>
    <fullName>CC_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Client is paying w. CC</description>
    <label>CC Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The business division to which this Opportunity applies. The Division Leader is responsible for closing this deal.</description>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Amount__c</fullName>
    <description>Formula Field which calculates  List Amount minus any applied Customer Discounts. 
Factors in CC Fee, Sales Tax, Deposit Amount Paid</description>
    <formula>IF (  AND(DATEVALUE(CreatedDate) &lt; DATE(2023,10,5),CC_Payment__c = TRUE), Amount +  CC_Fee_invoice__c + Tax_to_collect__c - Deposit_Amount_Paid__c, Amount + Tax_to_collect__c - Deposit_Amount_Paid__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula Field which calculates  List Amount minus any applied Customer Discounts. 
Factors in CC Fee, Sales Tax, Deposit Amount Paid</inlineHelpText>
    <label>Invoice - Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <description>This is an Invoice Number which is automatically created by Salesforce and delivered to Quickbooks via Workato, our Middleware. It&apos;s important for bookkeeping purposes as the Invoice Numbers in Salesforce must be identical to the Invoice Numbers in Quickbooks</description>
    <displayFormat>{0000}</displayFormat>
    <label>Invoice #</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <formula>TEXT( Account.Payment_Terms__c )</formula>
    <label>zPandadoc - Payment Terms - Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opp_Primary Contact (PrimaryContact__c) is a lookup field linking an Opportunity to its main Contact. It helps track key decision-makers, improve reporting, and enable automation. Used for CRM insights, sales follow-ups, and potential process automation. Ensure it&apos;s populated for accurate reporting and workflow triggers.</description>
    <label>Primary Contact (Opp)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities-Primary Contact</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tax_to_collect__c.field-meta.xml
<CustomField>
    <fullName>Tax_to_collect__c</fullName>
    <description>This Advanced Formula field sums the Total Taxable Quote Lines from the Primary Opportunity Quote.

Used in PandaDoc → Estimates &amp; invoices reference this field to calculate Sales Tax Amounts.
Not used in QuickBooks → QuickBooks applies sales tax automatically based on the &apos;Taxable&apos; field in Product Records.</description>
    <formula>SBQQ__PrimaryQuote__r.Total_tax__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Tax (Opp)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Upper_Descriptor__c.field-meta.xml
<CustomField>
    <fullName>Upper_Descriptor__c</fullName>
    <description>Makes field all CAPS for Pandadoc Estimates/Invoices</description>
    <formula>UPPER ( Opportunity_Descriptor__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Makes field all CAPS for Pandadoc Estimates/Invoices</inlineHelpText>
    <label>zPandadoc - Opportunity Descriptor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/selectors/OpportunitySelector.cls
public with sharing class OpportunitySelector {
    public OpportunitySelector() {

    }

    public List<Opportunity> selectOpportunitiesByIds(Set<Id> ids) {
        return [
            SELECT
              Name,
              Account.Name,
              CC_Payment__c,
              CC_Fee_invoice__c,
              Division__r.Name,
              InvoiceNumber__c,
              Upper_Descriptor__c,
              Payment__c,
              PrimaryContact__r.FirstName,
              PrimaryContact__r.LastName,
              PrimaryContact__r.Email,
              Tax_to_collect__c,
              Invoice_Amount__c
            FROM Opportunity
            WHERE Id IN :ids
        ];
    }
}