force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <description>A division of Slate&apos;s business, either &quot;Slate&quot;, &quot;Palermo&quot; or &quot;Align&quot; at time of writing.</description>
    <label>Division</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/Division_Leader__c.field-meta.xml
<CustomField>
    <fullName>Division_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The user who is responsible for closing deals opened within this business division</inlineHelpText>
    <label>Division Leader</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Divisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The business division to which this Opportunity applies. The Division Leader is responsible for closing this deal.</description>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <description>Svc Type (Required) – Must be entered when creating an Opp.
Syncs with Auto Quote Builder to generate quotes based on Svc Type.</description>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand Content</fullName>
                <label>Slate - Brand Content</label>
            </value>
            <value>
                <fullName>Slate - CGI</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
                <default>true</default>
                <label>Slate - eCom</label>
            </value>
            <value>
                <fullName>Motion</fullName>
                <label>Slate - Motion</label>
            </value>
            <value>
                <fullName>Retouching</fullName>
                <label>Slate - Retouch</label>
            </value>
            <value>
                <fullName>Studio Rental</fullName>
                <label>Slate - Studio &amp; Eq</label>
            </value>
            <value>
                <fullName>Retouching - Align</fullName>
                <label>Align - Retouch</label>
            </value>
            <value>
                <fullName>Palermo - Branding</fullName>
            </value>
            <value>
                <fullName>Palermo - Video Production</fullName>
                <label>Palermo - Content</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Post Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Post Production</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Production</label>
            </value>
            <value>
                <fullName>Palermo - Photo Production</fullName>
                <isActive>false</isActive>
                <label>Palermo - Photo Production</label>
            </value>
            <value>
                <fullName>Origins</fullName>
                <isActive>false</isActive>
                <label>Retouching - Origins</label>
            </value>
            <value>
                <fullName>Social Content</fullName>
                <isActive>false</isActive>
                <label>Social Content</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opp_Primary Contact (PrimaryContact__c) is a lookup field linking an Opportunity to its main Contact. It helps track key decision-makers, improve reporting, and enable automation. Used for CRM insights, sales follow-ups, and potential process automation. Ensure it&apos;s populated for accurate reporting and workflow triggers.</description>
    <label>Primary Contact (Opp)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities-Primary Contact</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <description>This Field is used to specify Service Type when a quote is being set up as a template for auto quote generation. (AutoQuoteGeneration Apex class) Auto Quote Generation works for all new opportunities created and generates a quote based on the Service Type using 3x Methods. If previous won opportunity for the account with the same service type exists, it clones the primary quote from this previous opportunity. If there isn&apos;t a previous won opportunities, it checks to see whether the account has an account</description>
    <inlineHelpText>This Field is used to specify Service Type when a quote is being set up as a template for auto quote generation. (AutoQuoteGeneration Apex class) Auto Quote Generation works for all new opportunities created and generates a quote based on the Service Type using 3x Methods. If previous won opportunity for the account with the same service type exists, it clones the primary quote from this previous opportunity. If there isn&apos;t a previous won opportunities, it checks to see whether the account has an account</inlineHelpText>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RecordsSharingServiceTest.cls
/**
 * @description : Test class covering sharing logics written in OpportunityTrigger, OpportunityContactRoleTrigger & QuoteTrigger
**/
@isTest
public class RecordsSharingServiceTest {
    
    @isTest
    static void testHandleContactSharingWithOCRInsertion() {
        Division__c division = new Division__c(Name='Slate', Division_Leader__c=UserInfo.getUserId());
        insert division;

        Account account = new Account(Name='Test Account');
        insert account;

        Opportunity opportunity = new Opportunity(Name='Test Opportunity', StageName='Open', CloseDate=Date.today(), AccountId=account.Id, Division__c=division.Id, Lead_Type__c = 'Slate - CGI');
        insert opportunity;

        Contact contact1 = new Contact(FirstName='Test1', LastName='User1', AccountId=account.Id, Email='test1@test.com');
        insert contact1;

        Test.startTest();
        OpportunityContactRole ocr = new OpportunityContactRole(OpportunityId=opportunity.Id, ContactId=contact1.Id, Role='Decision Maker');
        insert ocr;
        Test.stopTest();
        
        List<ContactShare> initialShares = [SELECT Id, ContactId, UserOrGroupId FROM ContactShare WHERE ContactId = :contact1.Id];
        Assert.areEqual(1, initialShares.size(), 'Expected one ContactShare record to be created');
    }
    @isTest
    static void testHandleContactSharingWithOCRUpdation() {
        Division__c division = new Division__c(Name='Slate', Division_Leader__c=UserInfo.getUserId());
        insert division;

        Account account = new Account(Name='Test Account');
        insert account;

        Opportunity opportunity = new Opportunity(Name='Test Opportunity', StageName='Open', CloseDate=Date.today(), AccountId=account.Id, Division__c=division.Id, Lead_Type__c = 'Slate - CGI');
        insert opportunity;

        Contact contact1 = new Contact(FirstName='Test1', LastName='User1', AccountId=account.Id, Email='test1@test.com');
        insert contact1;

        Contact contact2 = new Contact(FirstName='Test2', LastName='User2', AccountId=account.Id, Email='test2@test.com');
        insert contact2;        

        OpportunityContactRole ocr = new OpportunityContactRole(OpportunityId=opportunity.Id, ContactId=contact1.Id, Role='Decision Maker');
        insert ocr;
        
        Test.startTest();
        ocr.ContactId = contact2.Id;
        update ocr;
        Test.stopTest();
        
        List<ContactShare> newShares = [SELECT Id, ContactId, UserOrGroupId FROM ContactShare WHERE ContactId = :contact2.Id];
        Assert.areEqual(1, newShares.size(), 'Expected one ContactShare record for the new Contact');
        Assert.areEqual(division.Division_Leader__c, newShares[0].UserOrGroupId, 'The UserOrGroupId should match the Division Leader');

    }
    
    @isTest
    static void testHandleAccount_PrimaryContactSharing() {
        Division__c division = new Division__c(Name='Slate', Division_Leader__c=UserInfo.getUserId());
        insert division;

        Account account = new Account(Name='Test Account');
        insert account;

        Opportunity opportunity = new Opportunity(Name='Test Opportunity', StageName='Open', CloseDate=Date.today(), AccountId=account.Id, Division__c=division.Id, Lead_Type__c = 'Slate - CGI');
        insert opportunity;

        Contact contact = new Contact(FirstName='Test', LastName='User', AccountId=account.Id, Email='test@test.com');
        insert contact;

        Test.startTest();
        opportunity.PrimaryContact__c = contact.Id;
        update opportunity;
        Test.stopTest();

        List<AccountShare> accShares = [SELECT Id, AccountId, UserOrGroupId FROM AccountShare WHERE AccountId = :account.Id];
        Assert.areEqual(1, accShares.size(), 'Expected one AccountShare record to be created');
        Assert.areEqual(division.Division_Leader__c, accShares[0].UserOrGroupId, 'The UserOrGroupId should match the Division Leader');

        List<ContactShare> shares = [SELECT Id, ContactId, UserOrGroupId FROM ContactShare WHERE ContactId = :contact.Id];
        Assert.areEqual(1, shares.size(), 'Expected one ContactShare record to be created');
        Assert.areEqual(division.Division_Leader__c, shares[0].UserOrGroupId, 'The UserOrGroupId should match the Division Leader');
    }

    @isTest
    static void testHandleQuoteSharing() {
        Division__c division = new Division__c(Name='Slate', Division_Leader__c=UserInfo.getUserId());
        insert division;

        Account account = new Account(Name='Test Account');
        insert account;

        Opportunity opportunity = new Opportunity(Name='Test Opportunity', StageName='Open', CloseDate=Date.today(), AccountId=account.Id, Division__c=division.Id,Lead_Type__c = 'Slate - CGI');
        insert opportunity;

        Test.startTest();
        SBQQ__Quote__c quote = new SBQQ__Quote__c(SBQQ__Opportunity2__c=opportunity.Id, OwnerId=UserInfo.getUserId());
        insert quote;
        Test.stopTest();

        List<SBQQ__Quote__Share> shares = [SELECT Id, ParentId, UserOrGroupId FROM SBQQ__Quote__Share WHERE ParentId = :quote.Id];
        Assert.areEqual(1, shares.size(), 'Expected one Quote Share record to be created');
        Assert.areEqual(division.Division_Leader__c, shares[0].UserOrGroupId, 'The UserOrGroupId should match the Division Leader');
    }
}