force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <description>A division of Slate&apos;s business, either &quot;Slate&quot;, &quot;Palermo&quot; or &quot;Align&quot; at time of writing.</description>
    <label>Division</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/Division_Leader__c.field-meta.xml
<CustomField>
    <fullName>Division_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The user who is responsible for closing deals opened within this business division</inlineHelpText>
    <label>Division Leader</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Divisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The business division to which this Opportunity applies. The Division Leader is responsible for closing this deal.</description>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <description>Svc Type (Required) – Must be entered when creating an Opp.
Syncs with Auto Quote Builder to generate quotes based on Svc Type.</description>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand Content</fullName>
                <label>Slate - Brand Content</label>
            </value>
            <value>
                <fullName>Slate - CGI</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
                <default>true</default>
                <label>Slate - eCom</label>
            </value>
            <value>
                <fullName>Motion</fullName>
                <label>Slate - Motion</label>
            </value>
            <value>
                <fullName>Retouching</fullName>
                <label>Slate - Retouch</label>
            </value>
            <value>
                <fullName>Studio Rental</fullName>
                <label>Slate - Studio &amp; Eq</label>
            </value>
            <value>
                <fullName>Retouching - Align</fullName>
                <label>Align - Retouch</label>
            </value>
            <value>
                <fullName>Palermo - Branding</fullName>
            </value>
            <value>
                <fullName>Palermo - Video Production</fullName>
                <label>Palermo - Content</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Post Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Post Production</label>
            </value>
            <value>
                <fullName>Casablanca - Motion Production</fullName>
                <isActive>false</isActive>
                <label>Casablanca - Motion Production</label>
            </value>
            <value>
                <fullName>Palermo - Photo Production</fullName>
                <isActive>false</isActive>
                <label>Palermo - Photo Production</label>
            </value>
            <value>
                <fullName>Origins</fullName>
                <isActive>false</isActive>
                <label>Retouching - Origins</label>
            </value>
            <value>
                <fullName>Social Content</fullName>
                <isActive>false</isActive>
                <label>Social Content</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opp_Primary Contact (PrimaryContact__c) is a lookup field linking an Opportunity to its main Contact. It helps track key decision-makers, improve reporting, and enable automation. Used for CRM insights, sales follow-ups, and potential process automation. Ensure it&apos;s populated for accurate reporting and workflow triggers.</description>
    <label>Primary Contact (Opp)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities-Primary Contact</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <formula>IF(
    OR
    (ISPICKVAL(Lead_Type__c, &quot;Brand Content&quot;), 
    ISPICKVAL(Lead_Type__c, &quot;Slate - CGI&quot;), 
    ISPICKVAL(Lead_Type__c, &quot;E-Commerce&quot;), 
    ISPICKVAL(Lead_Type__c, &quot;Motion&quot;),
    ISPICKVAL(Lead_Type__c, &quot;Retouching&quot;), 
    ISPICKVAL(Lead_Type__c, &quot;Studio Rental&quot;)
    ), &quot;Slate&quot;,


IF(
    OR
    (ISPICKVAL(Lead_Type__c, &quot;Align - CGI&quot;), 
    ISPICKVAL(Lead_Type__c, &quot;Retouching - Align&quot;), 
    ISPICKVAL(Lead_Type__c, &quot;Align - Video Editing&quot;), 
    ISPICKVAL(Lead_Type__c,&quot;Align - VFX/Animation&quot;)
    ), &quot;Align&quot;,
IF(
    OR
    (ISPICKVAL(Lead_Type__c, &quot;Casablanca - Motion Production&quot;), 
    ISPICKVAL(Lead_Type__c, &quot;Casablanca - Motion Post Production&quot;)
    ), &quot;Casablanca&quot;,
IF(
    OR(ISPICKVAL(Lead_Type__c, &quot;Palermo - Branding&quot;), 
    ISPICKVAL(Lead_Type__c, &quot;Palermo - Video Production&quot;), 
    ISPICKVAL(Lead_Type__c, &quot;Palermo - CGI&quot;),
    ISPICKVAL(Lead_Type__c, &quot;Palermo - Digital/UX&quot;),
    ISPICKVAL(Lead_Type__c, &quot; Palermo - E-Commerce Content Production&quot;)
    ), &quot;Palermo&quot;,
     &quot;&quot;)

)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Type - Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <description>This Field is used to specify Service Type when a quote is being set up as a template for auto quote generation. (AutoQuoteGeneration Apex class) Auto Quote Generation works for all new opportunities created and generates a quote based on the Service Type using 3x Methods. If previous won opportunity for the account with the same service type exists, it clones the primary quote from this previous opportunity. If there isn&apos;t a previous won opportunities, it checks to see whether the account has an account</description>
    <inlineHelpText>This Field is used to specify Service Type when a quote is being set up as a template for auto quote generation. (AutoQuoteGeneration Apex class) Auto Quote Generation works for all new opportunities created and generates a quote based on the Service Type using 3x Methods. If previous won opportunity for the account with the same service type exists, it clones the primary quote from this previous opportunity. If there isn&apos;t a previous won opportunities, it checks to see whether the account has an account</inlineHelpText>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.
A primary quote must be selected for our Reporting/Dashboards to function properly.
The Primary Quote should be the most recent quote and/or the approved final customer quote</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
    <inlineHelpText>The Primary Customer Contact for the Quote. 
This is Main Opportunity Contact for the Opportunity the Quote is Related To</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/L4GControllerTest.cls
@isTest
public class L4GControllerTest {
    
    @testSetup
    public static void makeData(){
        Opportunity opp = new Opportunity(Name = 'Slate Studios', CloseDate = Date.today(), StageName = 'Qualification - Project');
        insert opp;
        Account acc = new Account(Name = 'Test Slate Account');
        insert acc;
        Contact con = new Contact(LastName = 'LastName', AccountId = acc.Id, Email = 'test@slate.com', Service_Type__c = 'E-Commerce');
        insert con;
        insert new OpportunityContactRole(ContactId = con.Id, OpportunityId = opp.Id);
        SBQQ__Quote__c quote = new SBQQ__Quote__c(SBQQ__Primary__c = true, SBQQ__PrimaryContact__c = con.Id, SBQQ__Opportunity2__c = opp.Id);
        insert quote;
        opp.SBQQ__PrimaryQuote__c = quote.Id;
        opp.PrimaryContact__c = con.Id;
        update opp;
        
        insert new Division__c(Division_Leader__c = UserInfo.getUserId(), Name = 'Slate');
    }
    
    @isTest
    public static void testGetFieldSet(){
        Test.startTest();
        List<L4GController.FieldWrapper> fields = L4GController.getFieldSet('L4G_NewContact','Contact');
        Test.stopTest();
        Assert.isTrue(!fields.IsEmpty());
    }
    @isTest
    public static void testFetchLookupData(){
        Test.startTest();
        List<SObject> sobjList = L4GController.fetchLookupData('Test','Account');
        Test.stopTest();
        Assert.isTrue(!sobjList.IsEmpty());
    }
    @IsTest
    public static void testGetAccountId(){
        Account acc = [SELECT Id, Name FROM Account LIMIT 1];
        Test.startTest();
        Id accId = L4GController.getAccountId('Test');
        Sobject accRecord = L4GController.fetchDefaultRecord(acc.Id,'Account');
        Test.stopTest();
        Assert.areEqual(acc.Name,(String)accRecord.get('Name'));
        Assert.areNotEqual(acc.Id, accId);
    }
    @isTest
    public static void testCheckIfContactExists(){
        Test.startTest();
        Map<String,String> existingContactsMap = L4GController.checkIfContactExists(new List<String>{'test@slate.com'});
        Test.stopTest();
        Assert.isTrue(existingContactsMap.containsKey('test@slate.com'));
    }
    @isTest
    public static void testCloneRecord(){
        Id oppId = [SELECT Id FROM Opportunity LIMIT 1].Id;
        Test.startTest();
        L4GController.cloneRecord(oppId, 'Test email body');
        Test.stopTest();
        Integer opportunityCount = [SELECT COUNT() FROM Opportunity];
        Assert.areEqual(2, opportunityCount);
    }
    @isTest
    public static void testGetFieldsToView(){
        Test.startTest();
        List<String> fields = L4GController.getFieldsToView('L4G_NewContact','Contact');
        Test.stopTest();
        Assert.isTrue(!fields.IsEmpty());
    }
    @isTest
    public static void testGetRelatedOpportunities(){
        Id conId = [Select id from Contact LIMIT 1].Id;
        Test.startTest();
        L4GController.getRelatedOpportunities(conId);
        Test.stopTest();
    }
    @isTest
    public static void testGetDivisionNames(){
        Test.startTest();
        List<String> divisions = L4GController.getDivisionNames();
        Test.stopTest();
        Assert.areEqual('Slate', divisions[0]);
    }
    @isTest
    public static void testGetPricebook(){
        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(
            Id = pricebookId,
            IsActive = true
        );
        update standardPricebook;
        Test.startTest();
        List<Pricebook2> pricebooks = L4GController.getPricebook();
        Test.stopTest();
        Assert.areEqual(standardPricebook.Id, pricebooks[0].Id);
    }
    @isTest
    public static void testQuoteLineTrigger(){
        Id conId = [Select id from contact limit 1].Id;
        Id quoteId = [Select id from SBQQ__Quote__c limit 1].Id;
        Product2 product = new Product2(Name = 'Test Product');
        insert product;
        Test.startTest();
        insert new SBQQ__QuoteLine__c(SBQQ__Quote__c = quoteId, Vendor__c = conId, Lead_Type__c = 'E-Commerce', SBQQ__Product__c = product.Id);            
        Test.stopTest();
        List<OpportunityContactRole> oppContactRoles = [SELECT Id FROM OpportunityContactRole WHERE ContactId = :conId];
        Assert.isTrue(!oppContactRoles.isEmpty());
    }

}